import React, { useEffect, useMemo, useState } from 'react'
import { api } from '../lib/api'

const initials = (name) => name.split(' ').map(part => part[0]).join('').slice(0, 2)
const percent = value => `${Number(value || 0)}%`

export default function AIAnalytics() {
  const [data, setData] = useState(null); const [query, setQuery] = useState(''); const [selected, setSelected] = useState(null); const [insights, setInsights] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [generating, setGenerating] = useState(false)
  const load = async () => { try { setData(await api.analytics()); setError('') } catch (requestError) { setError(requestError.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const employees = useMemo(() => (data?.employees || []).filter(employee => `${employee.full_name} ${employee.department}`.toLowerCase().includes(query.toLowerCase())), [data, query])
  const generate = async (employee = null) => { setSelected(employee); setGenerating(true); try { setInsights((await api.generateInsights(employee?.full_name)).insights); setError('') } catch (requestError) { setError(requestError.message) } finally { setGenerating(false) } }
  const totals = data?.totals || {}; const workflowTotal = (data?.workflowBreakdown || []).reduce((total, item) => total + Number(item.count), 0)
  if (loading) return <main className="ai-dashboard"><p>Loading live dashboard data...</p></main>
  return <main className="ai-dashboard"><div className="ai-heading"><div><h1>AI Analytic Dashboard</h1><p>Current database data.</p></div><div className="ai-actions"><button onClick={() => generate()} disabled={generating}>{generating ? 'Generating...' : 'Generate AI Insights'}</button></div></div>{error && <p className="ai-service-note">{error}</p>}<section className="ai-content"><div className="ai-main"><section className="ai-kpis">{[['Total employees', totals.total_employees], ['Average performance', percent(totals.average_performance)], ['Learning completion', percent(totals.learning_completion)], ['Succession ready', totals.succession_ready]].map(([label, value]) => <article key={label}><small>{label}</small><b>{value ?? '0'}</b><em>Current database value</em></article>)}</section><section className="ai-chart-row">{[['Active workflows', workflowTotal], ['Completed workflows', (data?.workflowBreakdown || []).filter(item => item.status === 'completed').reduce((total, item) => total + Number(item.count), 0)], ['Loaded at', new Date().toLocaleTimeString()]].map(([label, value]) => <article key={label}><small>{label}</small><b>{value}</b><span>Workflow records</span></article>)}</section><section className="ai-records"><div><h2>Employee performance and learning progress</h2><label className="employee-search"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search employee or department" /></label></div><table><thead><tr><th>Employee</th><th>Department</th><th>Performance</th><th>Learning progress</th></tr></thead><tbody>{employees.map((employee, index) => <tr key={employee.id} onClick={() => generate(employee)} className={selected?.id === employee.id ? 'selected-employee' : ''}><td><i className={`table-avatar av-${index}`}>{initials(employee.full_name)}</i>{employee.full_name}</td><td>{employee.department}</td><td>{percent(employee.performance_score)}</td><td>{percent(employee.learning_progress)}</td></tr>)}</tbody></table>{employees.length === 0 && <p className="no-results">No employee records match your search.</p>}</section></div><aside className="insight-panel"><div className="insight-title"><div><h2>{selected ? `${selected.full_name} analytics` : 'AI Insights'}</h2><p>{selected ? 'Individual employee view' : 'Organization view'}</p></div></div>{insights ? <div className="insight-results">{insights.map(insight => <article key={insight.title}><h3>{insight.title}</h3><p>{insight.summary}</p></article>)}</div> : <div className="insight-empty"><b>Ready to analyze</b><p>Choose an employee or generate an organization-wide summary from the current database data.</p></div>}</aside></section></main>
}
