import { useEffect, useMemo, useState } from 'react'
import SearchableSelector from './SearchableSelector'
import ModuleAIInsights from './ModuleAIInsights'
import { api } from '../lib/api'

const getRole = () => { try { return JSON.parse(localStorage.getItem('pds-user') || '{}').role } catch { return undefined } }
const moduleKeys = { 'Performance review': 'performance', 'Skill development': 'competency', 'Learning progress': 'learning', 'Training management': 'training', 'Succession planning': 'succession', 'Social recognition': 'recognition' }

export default function WorkflowPage({ title, description, action, items, itemLabel = 'Employee', module, itemIsEmployee = false }) {
  const role = getRole(); const moduleKey = module || moduleKeys[title]
  const [workflow, setWorkflow] = useState(null); const [workflows, setWorkflows] = useState([]); const [definitions, setDefinitions] = useState([]); const [events, setEvents] = useState([]); const [people, setPeople] = useState([]); const [subject, setSubject] = useState(null); const [selected, setSelected] = useState(items[0]); const [note, setNote] = useState(''); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [scheduleOpen, setScheduleOpen] = useState(false); const [schedule, setSchedule] = useState({ date: '', time: '09:00', venue: 'Hotel Learning Hub' })
  const roleAction = typeof action === 'string' ? action : action?.[role]
  const visibleStages = useMemo(() => definitions.filter(stage => stage.roles.includes(role)), [definitions, role])
  const itemOptions = useMemo(() => items.map(item => ({ value: item[0], label: item[0], description: item[1] })), [items])
  const load = async () => { setLoading(true); try { const [list, definitionResult, subjectResult] = await Promise.all([api.workflows(moduleKey), api.workflowDefinitions(), api.workflowSubjects()]); const active = list.workflows[0] || null; setWorkflows(list.workflows || []); setDefinitions(definitionResult.workflows[moduleKey] || []); setPeople(subjectResult.employees || []); setSubject(previous => previous || subjectResult.employees?.[0] || null); setWorkflow(active); setEvents(active ? (await api.workflow(active.id)).events || [] : []); setError('') } catch (requestError) { setError(requestError.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [moduleKey])
  const current = definitions.find(stage => stage.key === workflow?.current_stage); const canStart = Boolean(definitions[0]?.roles.includes(role)); const canAct = Boolean(workflow && current?.roles.includes(role)); const assigned = itemIsEmployee ? people.find(person => person.full_name.toLowerCase() === selected[0].toLowerCase()) : subject
  const start = async () => { if (role !== 'employee' && !assigned) return setError(`Select a valid ${itemLabel.toLowerCase()} first.`); setSaving(true); try { await api.createWorkflow({ module: moduleKey, title: `${title}: ${selected[0]}`, subjectEmployeeId: role === 'employee' ? undefined : assigned?.id, metadata: { selectedItem: selected[0], selectedItemStatus: selected[2], assignedEmployee: assigned?.full_name } }); setNotice(`${roleAction || 'Workflow'} started and saved to the database.`); await load() } catch (requestError) { setError(requestError.message) } finally { setSaving(false) } }
  const complete = async () => { setSaving(true); try { const result = await api.advanceWorkflow(workflow.id, { note: note || undefined, data: { selectedItem: selected[0] } }); setNote(''); setNotice(result.completed ? 'Workflow completed and recorded.' : `${current.label} completed. ${result.nextAction} is now awaiting its assigned role.`); await load() } catch (requestError) { setError(requestError.message) } finally { setSaving(false) } }
  const saveNote = async () => { if (!note.trim()) return setError('Add a note before saving.'); setSaving(true); try { await api.addWorkflowNote(workflow.id, { note, data: { selectedItem: selected[0] } }); setNote(''); setNotice('Note saved to the database audit history.'); await load() } catch (requestError) { setError(requestError.message) } finally { setSaving(false) } }
  const chooseWorkflow = async id => { const active = workflows.find(entry => entry.id === id); if (!active) return; setWorkflow(active); try { setEvents((await api.workflow(id)).events || []) } catch (requestError) { setError(requestError.message) } }
  const saveSchedule = async () => { if (!schedule.date) return setError('Select a training date.'); setSaving(true); try { await api.addWorkflowNote(workflow.id, { note: `Training scheduled: ${schedule.date} at ${schedule.time}, ${schedule.venue}.`, data: { type: 'training_schedule', ...schedule, training: selected[0] } }); setScheduleOpen(false); setNotice('Verified training schedule saved to the database.'); await load() } catch (requestError) { setError(requestError.message) } finally { setSaving(false) } }
  if (loading) return <main className="module-workspace"><div className="dashboard-skeleton"><i /><i /><i /><i /></div></main>
  const display = current?.label || definitions[0]?.label || 'Workflow'; const personOptions = people.map(person => ({ value: person.id, label: person.full_name, description: `${person.job_title} - ${person.department}` })); const stats = [['Active workflows', workflows.length], ['Current stage', workflow ? display : 'Not started'], ['Audit entries', events.length], ['Last updated', workflow ? new Date(workflow.updated_at).toLocaleTimeString() : '-']]
  return <main className="module-workspace">
    <div className="module-heading"><div><h1>{title}</h1><p>{description}</p></div>{roleAction && !workflow && <button onClick={start} disabled={!canStart || saving}>{saving ? 'Starting...' : roleAction}</button>}</div>
    {notice && <div className="module-notice">✓ {notice}</div>}{error && <div className="module-notice">{error}</div>}
    <section className="module-metrics">{stats.map(([label, value], index) => <article key={label}><span>{index + 1}</span><div><small>{label}</small><b>{value}</b><em>Live database value</em></div></article>)}</section>
    <section className="module-grid">
      <aside className="module-flow"><h2>{workflow ? 'Your assigned actions' : 'Your workflow'}</h2><div className="module-progress"><i style={{ width: `${workflow && canAct ? 100 : 0}%` }} /></div><small>{workflow ? canAct ? 'Action required from your role' : 'Waiting for another role' : canStart ? 'Ready to start' : 'No action assigned'}</small>{visibleStages.map(stage => <button key={stage.key} className={stage.key === workflow?.current_stage ? 'active' : ''}><span>{stage.key === workflow?.current_stage ? '•' : '○'}</span><div><b>{stage.label}</b><small>{stage.key === workflow?.current_stage ? 'Current action' : 'Your workflow action'}</small></div></button>)}</aside>
      <section className="module-process"><div className="module-process-head"><span>{workflow ? canAct ? 'Action required' : 'Read-only status' : 'Ready to start'}</span><b>{display}</b></div><div className="module-content"><h2>{display}</h2><p>{workflow ? canAct ? 'This step is assigned to your role. Complete it to update the database.' : 'This workflow is currently assigned to another role. No action controls are available.' : canStart ? 'Select a record, then start the workflow.' : 'Your role does not have a start action for this workflow.'}</p>{workflows.length > 1 && <label className="workflow-picker">View active workflow<select value={workflow?.id || ''} onChange={event => chooseWorkflow(event.target.value)}>{workflows.map(entry => <option key={entry.id} value={entry.id}>{entry.title}</option>)}</select></label>}{!workflow && canStart && <><SearchableSelector label={itemIsEmployee ? 'Assign employee' : `Select ${itemLabel}`} options={itemOptions} value={{ value: selected[0], label: selected[0], description: selected[1] }} onChange={option => setSelected(items.find(item => item[0] === option.value) || items[0])} />{role !== 'employee' && !itemIsEmployee && subject && <SearchableSelector label="Assign employee" options={personOptions} value={{ value: subject.id, label: subject.full_name, description: `${subject.job_title} - ${subject.department}` }} onChange={option => setSubject(people.find(person => person.id === option.value) || null)} />}</>}{workflow && <div className="module-data"><article><small>{itemLabel}</small><b>{selected[0]}</b><span>{selected[1]}</span></article><article><small>Workflow status</small><b>{workflow.status}</b><span>Current owner: {current?.roles.join(' / ')}</span></article></div>}<details open><summary>Audit history <span>⌄</span></summary>{events.length ? events.map(event => <p key={event.id}><b>{event.actor_name}</b> {event.event_type} {event.stage.replaceAll('_', ' ')} on {new Date(event.created_at).toLocaleString()}{event.note ? `: ${event.note}` : ''}</p>) : <p>Changes appear here after the workflow starts.</p>}</details>{workflow && canAct && <><details open><summary>Notes and attachments <span>⌄</span></summary><textarea value={note} onChange={event => setNote(event.target.value)} placeholder="Add a note or supporting context..." /></details>{moduleKey === 'training' && role === 'hr' && <button className="schedule-trigger" onClick={() => setScheduleOpen(true)}>Schedule verified enrollment</button>}</>}<div className="module-actions">{!workflow && canStart && <button className="module-primary" disabled={saving} onClick={start}>{saving ? 'Starting...' : `${roleAction || 'Start'} workflow`}</button>}{workflow && canAct && <><button disabled={saving} onClick={saveNote}>Save draft</button><button className="module-primary" disabled={saving} onClick={complete}>{saving ? 'Saving...' : `Complete ${display}`}</button></>}</div></div></section>
      <ModuleAIInsights module={moduleKey} stage={display} />
    </section>
    {scheduleOpen && <div className="schedule-backdrop" role="dialog" aria-modal="true"><section className="schedule-dialog"><div><h2>Schedule training</h2><p>Set session details after HR verifies enrollment.</p></div><label>Training date<input type="date" value={schedule.date} onChange={event => setSchedule({ ...schedule, date: event.target.value })} /></label><label>Start time<input type="time" value={schedule.time} onChange={event => setSchedule({ ...schedule, time: event.target.value })} /></label><label>Venue<input value={schedule.venue} onChange={event => setSchedule({ ...schedule, venue: event.target.value })} /></label><div><button onClick={() => setScheduleOpen(false)}>Cancel</button><button className="module-primary" disabled={saving} onClick={saveSchedule}>{saving ? 'Saving...' : 'Confirm schedule'}</button></div></section></div>}
  </main>
}
